[package]
name = "lil-vm"
version = "0.1.0"
authors = ["Lictor Guzman <lctrgzmn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# stringy = "0.2.2"
stringy = { git = "https://github.com/lctr/stringy" }